name: Manage labels

on:
  push:
    branches:
      - master

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.3.0

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-delete: true
